namespace Iql.JavaScript.JavaScriptExpressionToExpressionTree.Operators
{
    public enum OperatorType
    {
        And,
        Or,
        GreaterThan,
        GreaterThanOrEqualTo,
        LessThan,
        LessThanOrEqualTo,
        Assign,
        EqualsEquals,
        NotEquals,
        EqualsEqualsEquals,
        NotEqualsEquals,
        Not,
        Modulo,
        Subtract,
        Add,
        Multiply,
        Divide,
        SubtractOne,
        AddOne,
        SubtractEquals,
        AddEquals,
        MultiplyEquals,
        DivideEquals,
        BitwiseOr,
        Has,
        BitwiseNot
    }
}