namespace Iql
{
    public enum IqlType
    {
        Void,
        Unknown,
        Collection,
        Class,
        String,
        Integer,
        Decimal,
        Boolean,
        Date,
        Enum,
        TimeSpan,
        EnumValue,
        Guid,
        GeometryPoint,
        GeometryMultiPoint,
        GeometryPolygon,
        GeometryMultiPolygon,
        GeometryLine,
        GeometryMultiLine,
        GeometryRing,
        GeographyPoint,
        GeographyMultiPoint,
        GeographyPolygon,
        GeographyMultiPolygon,
        GeographyLine,
        GeographyMultiLine,
        GeographyRing
    }
}